version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - "CACHEBUST=$(date +%s)"
    ports:
      - '5000:5000'
    environment:
      - OPENAI-API-KEY
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - "CACHEBUST=$(date +%s)"
    ports:
      - '8080:80'
